name: Build Design Tokens

# 푸시할 때마다 실행
on:
  push:
    branches:
      - main
      - 'feat/**'  # 선택적으로 feature 브랜치도 가능

jobs:
  build:
    name: Transform and Build Design Tokens
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. 패키지 설치
      - name: Install dependencies
        run: npm ci

      # 4. 토큰 변환 (예: data/tokens.json → theme/global.json)
      - name: Transform tokens
        run: npm run global

      # 5. Style Dictionary로 빌드
      - name: Build design tokens
        run: npm run build

      # (선택) 6. 결과물을 커밋하고 푸시
      - name: Commit and push built tokens
        uses: EndBug/add-and-commit@v9
        with:
          message: "change design tokens"
          add: "build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}